heat_template_version: 2014-10-16
parameters:
  ssh_key_name:
    type: string
    label: SSH Key name
    description: User name to be configured for the application
    default: "@param:ssh-key-name"
  flavor:
    type: string
    default: 1GB Standard Instance
    constraints:
    - allowed_values:
      - 512MB Standard Instance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
resources:
  master_server:
    type: "OS::Nova::Server"
    properties:
      name: "master-@param:app-name"
      key_name: { get_param: ssh_key_name }
      flavor: { get_param: flavor }
      image: @param:core-os-image-id
      networks:
        - {uuid: 00000000-0000-0000-0000-000000000000}
        - {uuid: 11111111-1111-1111-1111-111111111111}
      user_data_format: RAW
      config_drive: "true"
      user_data: |
        @insert: "file:assets/master.heatit.yaml"
  nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: @param:nodes-count
      resource_def:
        type: OS::Nova::Server
        properties:
          name: node-%index%-@param:app-name
          key_name: { get_param: ssh_key_name }
          flavor: { get_param: flavor }
          image: @param:core-os-image-id
          networks:
            - {uuid: 00000000-0000-0000-0000-000000000000}
            - {uuid: 11111111-1111-1111-1111-111111111111}
          user_data_format: RAW
          config_drive: "true"
          user_data:
            str_replace:
              template: |
                @insert: "file:assets/node.heatit.yaml"
              params:
                $master_addr: { get_attr: [master_server, networks, private, 0] }
